# Himalaya Gmail Configuration

[accounts.gmail]
default = true
email = "camwest@gmail.com"
display-name = "Cameron Westland"
downloads-dir = "/tmp/himalaya/downloads"
signature = "Sent with Himalaya"

# IMAP backend configuration
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "camwest@gmail.com"
backend.auth.type = "password"
backend.auth.cmd = "echo $GMAIL_APP_PASSWORD"

# SMTP backend configuration for sending
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "camwest@gmail.com"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "echo $GMAIL_APP_PASSWORD"